"""
Quantization and C Header Export Pipeline for ESP32-S3 Edge AI.
Converts trained Keras model into Full-Integer INT8 TFLite FlatBuffer
and generates a production-ready C header (tinydriver_model_data.h).
"""

import os
import argparse
import numpy as np
import tensorflow as tf

try:
    from config import IMAGE_WIDTH, IMAGE_HEIGHT, NUM_LANDMARKS
    from wing_loss import AdaptiveBiometricWingLoss, WingLoss
    from dataset_loader import generate_synthetic_driver_sample
except (ImportError, ValueError):
    from .config import IMAGE_WIDTH, IMAGE_HEIGHT, NUM_LANDMARKS
    from .wing_loss import AdaptiveBiometricWingLoss, WingLoss
    from .dataset_loader import generate_synthetic_driver_sample


def representative_dataset_gen(num_samples=300):
    """Generates sample float32 batches for integer quantization calibration (33% closed, 33% yawn, 34% normal)."""
    states = ['microsleep', 'yawn', 'normal']
    for i in range(num_samples):
        force_st = states[i % 3]
        img, _, _ = generate_synthetic_driver_sample(i, apply_aug=True, force_state=force_st)
        # Normalize to [-1.0, 1.0]
        img_norm = (img.astype(np.float32) - 128.0) / 128.0
        yield [np.expand_dims(img_norm, axis=0)]


def convert_model_to_c_array(tflite_bytes, output_header_path, input_scale, input_zp, output_scale, output_zp, output_is_float=True):
    """Formats tflite binary into 16-byte aligned C array with metadata defines."""
    tflite_len = len(tflite_bytes)

    with open(output_header_path, 'w') as f:
        f.write("/**\n")
        f.write(" * Auto-generated by export_tflite.py for ESP32-S3 N16R8 Edge AI.\n")
        f.write(f" * TinyDriver PFLD-Edge LandmarkNet ({'Mixed-Precision INT8/Float32' if output_is_float else 'Full-Integer INT8'} Model)\n")
        f.write(f" * Model Size: {tflite_len:,} bytes ({tflite_len / 1024.0:.1f} KB)\n")
        f.write(" */\n\n")
        f.write("#ifndef TINYDRIVER_MODEL_DATA_H_\n")
        f.write("#define TINYDRIVER_MODEL_DATA_H_\n\n")
        f.write("#include <stdint.h>\n\n")

        # Model Dimensions and Quantization Constants
        f.write("// Model Tensor Dimensions\n")
        f.write(f"#define TINYDRIVER_INPUT_WIDTH          {IMAGE_WIDTH}\n")
        f.write(f"#define TINYDRIVER_INPUT_HEIGHT         {IMAGE_HEIGHT}\n")
        f.write(f"#define TINYDRIVER_INPUT_CHANNELS       1\n")
        f.write(f"#define TINYDRIVER_NUM_LANDMARKS        {NUM_LANDMARKS}\n")
        f.write(f"#define TINYDRIVER_OUTPUT_DIMS          {NUM_LANDMARKS * 2}\n\n")

        f.write("// Output Precision Mode (1 = Float32 sub-pixel precision, 0 = INT8 quantized)\n")
        f.write(f"#define TINYDRIVER_OUTPUT_IS_FLOAT      {1 if output_is_float else 0}\n\n")

        f.write("// Quantization Parameters\n")
        f.write(f"#define TINYDRIVER_INPUT_SCALE          {input_scale:.8f}f\n")
        f.write(f"#define TINYDRIVER_INPUT_ZERO_POINT     {input_zp}\n")
        f.write(f"#define TINYDRIVER_OUTPUT_SCALE         {output_scale:.8f}f\n")
        f.write(f"#define TINYDRIVER_OUTPUT_ZERO_POINT    {output_zp}\n\n")

        # 16-byte alignment required for Xtensa LX7 SIMD 128-bit vector instructions (esp-nn)
        f.write("// Model Byte Array (Aligned to 16 bytes for esp-nn vector load)\n")
        f.write("const unsigned char g_tinydriver_model[] __attribute__((aligned(16))) = {\n")

        # Write bytes in hex, 12 bytes per line
        hex_bytes = [f"0x{b:02x}" for b in tflite_bytes]
        for i in range(0, len(hex_bytes), 12):
            chunk = hex_bytes[i:i + 12]
            f.write("    " + ", ".join(chunk) + ",\n")

        f.write("};\n\n")
        f.write(f"const unsigned int g_tinydriver_model_len = {tflite_len};\n\n")
        f.write("#endif // TINYDRIVER_MODEL_DATA_H_\n")

    print(f"[Export] Đã xuất file C Header thành công tại: {output_header_path}")


def main():
    parser = argparse.ArgumentParser(description="Export TinyDriverNet to TFLite and C Header")
    parser.add_argument("--model_path", type=str, default="./output/tinydriver_best.keras",
                        help="Path to trained Keras model")
    parser.add_argument("--output_dir", type=str, default="./output",
                        help="Directory to save exported files")
    parser.add_argument("--full_int8", action="store_true",
                        help="Enforce INT8 output instead of default Mixed-Precision (Float32 output)")
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)
    use_float_out = not args.full_int8

    print("=" * 65)
    print("📦 BẮT ĐẦU QUÁ TRÌNH LƯỢNG TỬ HÓA VÀ XUẤT MÔ HÌNH CHO ESP32-S3")
    print(f"👉 Nguồn mô hình: {args.model_path}")
    print(f"👉 Chế độ đầu ra: {'Mixed-Precision (Float32 Sub-Pixel)' if use_float_out else 'Full-Integer INT8'}")
    print("=" * 65)

    # 1. Load Keras Model
    if not os.path.exists(args.model_path):
        raise FileNotFoundError(f"Không tìm thấy mô hình tại {args.model_path}. Vui lòng chạy train trước!")

    custom_objects = {
        "AdaptiveBiometricWingLoss": AdaptiveBiometricWingLoss,
        "WingLoss": WingLoss
    }
    model = tf.keras.models.load_model(args.model_path, custom_objects=custom_objects)
    print(f"[Model] Nạp thành công mô hình với {model.count_params():,} tham số.")

    # Extract landmark deployment model
    if isinstance(model.output, dict) and "landmarks_output" in model.output:
        deploy_model = tf.keras.Model(inputs=model.input, outputs=model.output["landmarks_output"], name="Deploy_Landmarks")
    elif isinstance(model.output, (list, tuple)) and len(model.output) > 1:
        deploy_model = tf.keras.Model(inputs=model.input, outputs=model.output[0], name="Deploy_Landmarks")
    else:
        deploy_model = model

    print(f"[Deploy Model] Xuất mô hình Landmark-Only: {deploy_model.output_shape}")

    # 2. Configure Quantization using Concrete Function (Static Graph for MCU)
    run_model = tf.function(lambda x: deploy_model(x, training=False))
    concrete_func = run_model.get_concrete_function(
        tf.TensorSpec([1, IMAGE_HEIGHT, IMAGE_WIDTH, 1], tf.float32)
    )

    converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset_gen

    if use_float_out:
        # Mixed Precision: intermediate layers INT8, input INT8, output Float32
        converter.target_spec.supported_ops = [
            tf.lite.OpsSet.TFLITE_BUILTINS_INT8,
            tf.lite.OpsSet.TFLITE_BUILTINS
        ]
        converter.inference_input_type = tf.int8
        converter.inference_output_type = tf.float32
        print("[Quantization] Áp dụng Mixed-Precision (Convs INT8 + Regression Head Float32)...")
    else:
        # Full INT8
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        converter.inference_input_type = tf.int8
        converter.inference_output_type = tf.int8
        print("[Quantization] Áp dụng Full-Integer INT8...")

    tflite_quant_model = converter.convert()

    # 3. Save .tflite binary
    tflite_path = os.path.join(args.output_dir, "tinydriver_model.tflite")
    with open(tflite_path, "wb") as f:
        f.write(tflite_quant_model)

    file_size_kb = len(tflite_quant_model) / 1024.0
    print(f"[Save] Đã xuất file FlatBuffer: {tflite_path} ({file_size_kb:.1f} KB)")

    # 4. Verify Quantized Model
    input_scale, input_zp = 0.007843137, 0
    output_scale, output_zp = 1.0, 0
    output_is_float = use_float_out

    # Try allocating with ai_edge_litert or tf.lite
    interpreter = None
    try:
        from ai_edge_litert.interpreter import Interpreter
        interpreter = Interpreter(model_path=tflite_path)
        interpreter.allocate_tensors()
    except Exception:
        try:
            interpreter = tf.lite.Interpreter(model_path=tflite_path)
            interpreter.allocate_tensors()
        except Exception:
            interpreter = None

    if interpreter is not None:
        input_details = interpreter.get_input_details()[0]
        output_details = interpreter.get_output_details()[0]

        input_scale, input_zp = input_details["quantization"]
        if input_scale == 0.0:
            input_scale = 1.0 / 128.0
            input_zp = 0

        output_scale, output_zp = output_details["quantization"]
        output_is_float = (output_details["dtype"] == np.float32)

        print(f"\n[Verification] Kiểm chuẩn thông số lượng tử hóa:")
        print(f" - Input Shape: {input_details['shape']}, Dtype: {input_details['dtype']}")
        print(f" - Input Scale: {input_scale:.6f}, Zero-Point: {input_zp}")
        print(f" - Output Shape: {output_details['shape']}, Dtype: {output_details['dtype']}")
        print(f" - Output Is Float: {output_is_float}")
        if not output_is_float:
            print(f" - Output Scale: {output_scale:.6f}, Zero-Point: {output_zp}")

        # Test dummy inference
        dummy_input = np.zeros(input_details["shape"], dtype=np.int8)
        interpreter.set_tensor(input_details["index"], dummy_input)
        interpreter.invoke()
        output_val = interpreter.get_tensor(output_details["index"])
        print(f"[Verification] Test Invoke thành công! Output shape: {output_val.shape}, Sample: {output_val[0, :3]}")

    # 5. Export C Header File for ESP32-S3 Firmware
    header_path = os.path.join(args.output_dir, "tinydriver_model_data.h")
    convert_model_to_c_array(
        tflite_quant_model,
        header_path,
        input_scale, input_zp,
        output_scale, output_zp,
        output_is_float=output_is_float
    )

    print("\n" + "=" * 65)


if __name__ == "__main__":
    main()

