"""
Quantization and C Header Export Pipeline for ESP32-S3 Edge AI.
Converts trained Keras model into Full-Integer INT8 TFLite FlatBuffer
and generates a production-ready C header (tinydriver_model_data.h).
"""

import os
import argparse
import numpy as np
import tensorflow as tf

try:
    from config import IMAGE_WIDTH, IMAGE_HEIGHT, NUM_LANDMARKS
    from wing_loss import WingLoss
    from dataset_loader import generate_synthetic_driver_sample
except (ImportError, ValueError):
    from .config import IMAGE_WIDTH, IMAGE_HEIGHT, NUM_LANDMARKS
    from .wing_loss import WingLoss
    from .dataset_loader import generate_synthetic_driver_sample

def representative_dataset_gen(num_samples=300):
    """Generates sample float32 batches for integer quantization calibration."""
    for i in range(num_samples):
        img, _ = generate_synthetic_driver_sample(i)
        # Normalize to [-1.0, 1.0]
        img_norm = (img.astype(np.float32) - 128.0) / 128.0
        yield [np.expand_dims(img_norm, axis=0)]


def convert_model_to_c_array(tflite_bytes, output_header_path, input_scale, input_zp, output_scale, output_zp):
    """Formats tflite binary into 16-byte aligned C array with metadata defines."""
    tflite_len = len(tflite_bytes)
    
    with open(output_header_path, 'w') as f:
        f.write("/**\n")
        f.write(" * Auto-generated by export_tflite.py for ESP32-S3 N16R8 Edge AI.\n")
        f.write(" * TinyDriver-LandmarkNet (Full-Integer INT8 Quantized Model)\n")
        f.write(f" * Model Size: {tflite_len:,} bytes ({tflite_len / 1024.0:.1f} KB)\n")
        f.write(" */\n\n")
        f.write("#ifndef TINYDRIVER_MODEL_DATA_H_\n")
        f.write("#define TINYDRIVER_MODEL_DATA_H_\n\n")
        f.write("#include <stdint.h>\n\n")
        
        # Model Dimensions and Quantization Constants
        f.write("// Model Tensor Dimensions\n")
        f.write(f"#define TINYDRIVER_INPUT_WIDTH          {IMAGE_WIDTH}\n")
        f.write(f"#define TINYDRIVER_INPUT_HEIGHT         {IMAGE_HEIGHT}\n")
        f.write(f"#define TINYDRIVER_INPUT_CHANNELS       1\n")
        f.write(f"#define TINYDRIVER_NUM_LANDMARKS        {NUM_LANDMARKS}\n")
        f.write(f"#define TINYDRIVER_OUTPUT_DIMS          {NUM_LANDMARKS * 2}\n\n")
        
        f.write("// Quantization Parameters (INT8 Dequantization on ESP32)\n")
        f.write(f"#define TINYDRIVER_INPUT_SCALE          {input_scale:.8f}f\n")
        f.write(f"#define TINYDRIVER_INPUT_ZERO_POINT     {input_zp}\n")
        f.write(f"#define TINYDRIVER_OUTPUT_SCALE         {output_scale:.8f}f\n")
        f.write(f"#define TINYDRIVER_OUTPUT_ZERO_POINT    {output_zp}\n\n")
        
        # 16-byte alignment required for Xtensa LX7 SIMD 128-bit vector instructions (esp-nn)
        f.write("// Model Byte Array (Aligned to 16 bytes for esp-nn vector load)\n")
        f.write("const unsigned char g_tinydriver_model[] __attribute__((aligned(16))) = {\n")
        
        # Write bytes in hex, 12 bytes per line
        hex_bytes = [f"0x{b:02x}" for b in tflite_bytes]
        for i in range(0, len(hex_bytes), 12):
            chunk = hex_bytes[i:i + 12]
            f.write("    " + ", ".join(chunk) + ",\n")
            
        f.write("};\n\n")
        f.write(f"const unsigned int g_tinydriver_model_len = {tflite_len};\n\n")
        f.write("#endif // TINYDRIVER_MODEL_DATA_H_\n")

    print(f"[Export] Đã xuất file C Header thành công tại: {output_header_path}")


def main():
    parser = argparse.ArgumentParser(description="Export TinyDriverNet to TFLite INT8 and C Header")
    parser.add_argument("--model_path", type=str, default="./output/tinydriver_best.keras",
                        help="Path to trained Keras model")
    parser.add_argument("--output_dir", type=str, default="./output",
                        help="Directory to save exported files")
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)
    print("=" * 60)
    print("📦 BẮT ĐẦU QUÁ TRÌNH LƯỢNG TỬ HÓA FULL-INTEGER INT8")
    print(f"👉 Nguồn mô hình: {args.model_path}")
    print("=" * 60)

    # 1. Load Keras Model
    if not os.path.exists(args.model_path):
        raise FileNotFoundError(f"Không tìm thấy mô hình tại {args.model_path}. Vui lòng chạy train.py trước!")

    custom_objects = {"WingLoss": WingLoss}
    model = tf.keras.models.load_model(args.model_path, custom_objects=custom_objects)
    print(f"[Model] Nạp thành công mô hình với {model.count_params():,} tham số.")

    # 2. Configure Full-Integer Quantization
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_dataset_gen
    
    # Enforce full INT8 for both weights and activations (no float fallback)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    print("[Quantization] Đang hiệu chuẩn và lượng tử hóa INT8...")
    tflite_quant_model = converter.convert()

    # 3. Save .tflite binary
    tflite_path = os.path.join(args.output_dir, "tinydriver_model.tflite")
    with open(tflite_path, "wb") as f:
        f.write(tflite_quant_model)
        
    file_size_kb = len(tflite_quant_model) / 1024.0
    print(f"[Save] Đã xuất file FlatBuffer: {tflite_path} ({file_size_kb:.1f} KB)")

    # 4. Verify Quantized Model with TFLite Interpreter
    interpreter = tf.lite.Interpreter(model_content=tflite_quant_model)
    interpreter.allocate_tensors()

    input_details = interpreter.get_input_details()[0]
    output_details = interpreter.get_output_details()[0]

    input_scale, input_zp = input_details["quantization"]
    output_scale, output_zp = output_details["quantization"]

    print(f"\n[Verification] Kiểm chuẩn thông số lượng tử hóa:")
    print(f" - Input Shape: {input_details['shape']}, Dtype: {input_details['dtype']}")
    print(f" - Input Scale: {input_scale:.6f}, Zero-Point: {input_zp}")
    print(f" - Output Shape: {output_details['shape']}, Dtype: {output_details['dtype']}")
    print(f" - Output Scale: {output_scale:.6f}, Zero-Point: {output_zp}")

    # Test dummy inference
    dummy_input = np.zeros(input_details["shape"], dtype=np.int8)
    interpreter.set_tensor(input_details["index"], dummy_input)
    interpreter.invoke()
    output_val = interpreter.get_tensor(output_details["index"])
    print(f"[Verification] Test Invoke thành công! Output shape: {output_val.shape}")

    # 5. Export C Header File for ESP32-S3 Firmware
    header_path = os.path.join(args.output_dir, "tinydriver_model_data.h")
    convert_model_to_c_array(
        tflite_quant_model,
        header_path,
        input_scale, input_zp,
        output_scale, output_zp
    )

    print("\n" + "=" * 60)
    print("🎉 HOÀN TẤT XUẤT MÔ HÌNH INT8 CHO ESP32-S3!")
    print(f"1. File FlatBuffer : {tflite_path}")
    print(f"2. File C Header   : {header_path}")
    print("=" * 60)


if __name__ == "__main__":
    main()
